# Generated by Django 4.2.3 on 2023-08-31 09:30

import capital.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zonal_station', models.CharField(choices=[('abuja', 'Abuja'), ('enugu', 'Enugu'), ('headquaters', 'Headquaters'), ('ibadan', 'Ibadan'), ('kaduna', 'Kaduna'), ('lagos', 'Lagos'), ('northc', 'Northc'), ('south', 'South'), ('northe', 'Northe')], max_length=100)),
                ('type', models.CharField(choices=[('working', 'Working'), ('equity', 'Equity'), ('dept', 'Dept'), ('fixed', 'Fixed'), ('operating', 'Operating'), ('resk', 'Resk'), ('venture', 'Venture'), ('human', 'Human')], max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discription', models.TextField(max_length=200)),
                ('code', models.CharField(max_length=200, null=True)),
                ('supporting_documents', models.FileField(null=True, upload_to='capital/', validators=[capital.models.validate_image_size])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remark', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
