# Generated by Django 4.2.3 on 2024-01-24 10:58

import capital.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0013_alter_capital_supporting_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zonal_station', models.CharField(choices=[('abuja', 'Abuja'), ('enugu', 'Enugu'), ('headquaters', 'Headquaters'), ('ibadan', 'Ibadan'), ('kaduna', 'Kaduna'), ('lagos', 'Lagos'), ('northc', 'Northc'), ('south', 'South'), ('northe', 'Northe')], max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discription', models.TextField(max_length=200)),
                ('code', models.CharField(max_length=200, null=True)),
                ('supporting_documents', models.FileField(null=True, upload_to='overhead/', validators=[capital.models.validate_image_size])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remark', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='capital',
            name='supporting_documents',
            field=models.FileField(null=True, upload_to='capital/', validators=[capital.models.validate_image_size]),
        ),
    ]
