# Generated by Django 4.2.3 on 2024-02-01 17:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import invoicing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0002_contractor_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee', models.CharField(max_length=50)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('code', models.CharField(max_length=10, null=True)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('withholding_tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stamp_duty_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('withholding_tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stamp_duty_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StaffClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('staff_number', models.CharField(max_length=10)),
                ('ipps_number', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10, null=True)),
                ('office', models.CharField(max_length=200)),
                ('gl', models.CharField(max_length=10)),
                ('step', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=200)),
                ('degnisation', models.CharField(max_length=200)),
                ('station', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=200, null=True)),
                ('bank', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('sort_code', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ContractPaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('withholding_tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stamp_duty_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('withholding_tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stamp_duty_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('supporting_documents', models.FileField(null=True, upload_to='contract_payment/', validators=[invoicing.models.validate_image_size])),
                ('is_approved', models.CharField(choices=[('processing', 'processing'), ('audited', 'Audited'), ('approved', 'Approved'), ('paid', 'Paid')], default='processing', max_length=20)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.contractor')),
            ],
        ),
    ]
