# Generated by Django 4.2.3 on 2024-01-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractpaymentvoucher',
            old_name='payee',
            new_name='payee_id',
        ),
    ]
