# Generated by Django 4.2.3 on 2024-02-05 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffclaim',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
