# Generated by Django 4.2.3 on 2024-01-23 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractpaymentvoucher',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.contractor'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='payee',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='stamp_duty_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='staffclaim',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
