# Generated by Django 4.2.3 on 2024-01-23 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
        ('invoicing', '0002_alter_contractpaymentvoucher_payee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractpaymentvoucher',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.contractor'),
        ),
        migrations.DeleteModel(
            name='Contractor',
        ),
    ]
