# Generated by Django 4.2.3 on 2024-01-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_rename_payee_contractpaymentvoucher_payee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractpaymentvoucher',
            old_name='payee_id',
            new_name='payee',
        ),
    ]
