# Generated by Django 4.2.3 on 2024-01-25 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_alter_contractpaymentvoucher_payee_delete_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucher',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
