# Generated by Django 4.2.3 on 2024-01-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_alter_paymentvoucher_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffclaim',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
