# Generated by Django 4.2.3 on 2024-01-28 16:26

from django.db import migrations, models
import invoicing.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_staffclaim_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractpaymentvoucher',
            name='is_approved',
            field=models.CharField(choices=[('processing', 'processing'), ('approved', 'Approved'), ('reviewed', 'reviewed'), ('audited', 'Audited'), ('paid', 'Paid')], default='processing', max_length=20),
        ),
        migrations.AddField(
            model_name='contractpaymentvoucher',
            name='supporting_documents',
            field=models.FileField(null=True, upload_to='contract_payment/', validators=[invoicing.models.validate_image_size]),
        ),
    ]
