# Generated by Django 4.2.3 on 2024-01-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_alter_contractpaymentvoucher_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractpaymentvoucher',
            name='is_approved',
            field=models.CharField(choices=[('processing', 'processing'), ('audited', 'Audited'), ('approved', 'Approved'), ('paid', 'Paid')], default='processing', max_length=20),
        ),
    ]
