# Generated by Django 4.2.3 on 2024-01-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conpss_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conpss_peculiar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shift_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nhf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pension', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('union_dues', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ctss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cooptrative', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateTimeField()),
            ],
        ),
    ]
