# Generated by Django 4.2.3 on 2024-01-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, null=True, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('staff_number', models.CharField(max_length=10, unique=True)),
                ('ipps_number', models.CharField(max_length=10, unique=True)),
                ('office', models.CharField(max_length=200)),
                ('gl', models.CharField(max_length=10)),
                ('step', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=200)),
                ('degnisation', models.CharField(max_length=200)),
                ('station', models.CharField(max_length=200)),
                ('dob', models.DateField(null=True)),
                ('doa', models.DateField(null=True)),
                ('union', models.CharField(max_length=200, null=True)),
                ('account_number', models.CharField(max_length=200)),
                ('bank', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('sort_code', models.CharField(max_length=200)),
                ('conpss_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conpss_peculiar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shift_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nhf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pension', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('union_dues', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ctss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cooptrative', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateTimeField()),
            ],
        ),
    ]
