# Generated by Django 4.2.3 on 2024-02-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conpss_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conpss_peculiar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shift_allowance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('gross_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('nhf', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pension', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('union_dues', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ctss', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cooptrative', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateTimeField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
