# Generated by Django 4.2.3 on 2024-01-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='doa',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='dob',
        ),
    ]
