# Generated by Django 4.2.3 on 2024-02-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payroll_cooptrative_alter_payroll_ctss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='gl',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='step',
            field=models.CharField(max_length=20),
        ),
    ]
