# Generated by Django 4.2.3 on 2023-07-16 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('staff_number', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('account', 'Account'), ('audit', 'Audit')], default='staff', max_length=20)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_number', models.CharField(max_length=200)),
                ('bank', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('sort_code', models.CharField(max_length=200)),
                ('discription', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200, null=True)),
                ('supporting_documents', models.ImageField(null=True, upload_to='cash_advance/', validators=[user.models.validate_image_size])),
                ('application_date', models.DateTimeField(auto_now=True)),
                ('account_remark', models.CharField(max_length=200)),
                ('is_approved', models.CharField(choices=[('processing', 'processing'), ('manager', 'Manager'), ('account', 'Account'), ('audit', 'Audit'), ('paid', 'Paid')], default='processing', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetirementVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('amount_granted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_number', models.CharField(max_length=200)),
                ('bank', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('sort_code', models.CharField(max_length=200)),
                ('discription', models.CharField(max_length=200, null=True)),
                ('code', models.CharField(max_length=200)),
                ('supporting_documents', models.ImageField(null=True, upload_to='retirement_voucher/', validators=[user.models.validate_image_size])),
                ('application_date', models.DateTimeField(auto_now=True)),
                ('account_remark', models.CharField(max_length=200)),
                ('is_approved', models.CharField(choices=[('processing', 'processing'), ('manager', 'Manager'), ('account', 'Account'), ('audit', 'Audit'), ('retired', 'Retired')], default='processing', max_length=20)),
                ('cash_advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cashadvance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('office', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('others', models.CharField(max_length=200)),
                ('station', models.CharField(max_length=200)),
                ('dob', models.DateField(null=True)),
                ('profile', models.ImageField(default='default.jpg', upload_to='profile_images/')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
