# Generated by Django 4.2.3 on 2024-02-23 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('staff_number', models.CharField(max_length=10, unique=True)),
                ('ipps_number', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('account', 'Account'), ('audit', 'Audit')], default='staff', max_length=20)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('tax_state', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=200)),
                ('gl', models.CharField(max_length=10)),
                ('step', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=200)),
                ('degnisation', models.CharField(max_length=200)),
                ('station', models.CharField(max_length=200)),
                ('dob', models.DateField(null=True)),
                ('doa', models.DateField(null=True)),
                ('union', models.CharField(max_length=200, null=True)),
                ('account_number', models.CharField(max_length=200)),
                ('bank', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('sort_code', models.CharField(max_length=200)),
                ('pfa_name', models.CharField(max_length=200)),
                ('pension_pin', models.CharField(max_length=200)),
                ('profile', models.ImageField(default='default.jpg', upload_to='profile_images/')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
