# Generated by Django 4.2.3 on 2023-08-19 16:00

from django.db import migrations, models
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zonal_station', models.CharField(max_length=200)),
                ('discription', models.TextField(max_length=200)),
                ('code', models.CharField(max_length=200, null=True)),
                ('supporting_documents', models.FileField(null=True, upload_to='cash_advance/', validators=[user.models.validate_image_size])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(choices=[('working', 'Working'), ('equity', 'Equity'), ('dept', 'Dept'), ('fixed', 'Fixed'), ('operating', 'Operating'), ('resk', 'Resk'), ('venture', 'Venture'), ('human', 'Human')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='cashadvance',
            name='supporting_documents',
            field=models.FileField(null=True, upload_to='cash_advance/', validators=[user.models.validate_image_size]),
        ),
    ]
