# Generated by Django 4.2.3 on 2023-07-16 11:18

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashadvance',
            name='account_remark',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cashadvance',
            name='supporting_documents',
            field=models.FileField(null=True, upload_to='cash_advance/', validators=[user.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='retirementvoucher',
            name='account_remark',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='retirementvoucher',
            name='supporting_documents',
            field=models.FileField(null=True, upload_to='retirement_voucher/', validators=[user.models.validate_image_size]),
        ),
    ]
