# Generated by Django 4.2.3 on 2023-07-16 11:21

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_cashadvance_account_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashadvance',
            name='discription',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cashadvance',
            name='supporting_documents',
            field=models.FileField(null=True, upload_to='cash_advance/', validators=[user.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='cashadvance',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='retirementvoucher',
            name='discription',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='retirementvoucher',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
