# Generated by Django 4.2.3 on 2023-08-19 16:18

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_capital_zonal_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashadvance',
            name='supporting_documents',
            field=models.FileField(null=True, upload_to='cash_advance/', validators=[user.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='retirementvoucher',
            name='supporting_documents',
            field=models.FileField(null=True, upload_to='retirement_voucher/', validators=[user.models.validate_image_size]),
        ),
    ]
