# Generated by Django 4.2.3 on 2023-08-21 09:21

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_cashadvance_supporting_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='zonal_station',
            field=models.CharField(choices=[('abuja', 'Abuja'), ('enugu', 'Enugu'), ('headquaters', 'Headquaters'), ('ibadan', 'Ibadan'), ('kaduna', 'Kaduna'), ('lagos', 'Lagos'), ('northc', 'Northc'), ('south', 'South'), ('northe', 'Northe')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cashadvance',
            name='supporting_documents',
            field=models.FileField(null=True, upload_to='cash_advance/', validators=[user.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='retirementvoucher',
            name='supporting_documents',
            field=models.FileField(null=True, upload_to='retirement_voucher/', validators=[user.models.validate_image_size]),
        ),
    ]
