# Generated by Django 4.2.3 on 2023-08-30 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import retirement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashadvance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetirementVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('amount_granted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_number', models.CharField(max_length=200)),
                ('bank', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('sort_code', models.CharField(max_length=200)),
                ('discription', models.TextField(max_length=200, null=True)),
                ('code', models.CharField(max_length=200)),
                ('supporting_documents', models.FileField(null=True, upload_to='retirement_voucher/', validators=[retirement.models.validate_image_size])),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_remark', models.CharField(max_length=200, null=True)),
                ('is_approved', models.CharField(choices=[('processing', 'processing'), ('approved', 'Approved'), ('reviewed', 'reviewed'), ('audited', 'Audited'), ('paid', 'Paid')], default='processing', max_length=20)),
                ('cash_advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashadvance.cashadvance')),
            ],
        ),
    ]
